[ds]
    [ds.mysql]
		dsn = "root:zqwW4XYLzNwN3Dsa@tcp(54.72.185.137:3306)/test?parseTime=true"
		LogLimit = 100
        OrderLimit = 40
	[ds.redis]
		port = 6379
		chan = "orders"
[srv]
    ip = "0.0.0.0:"
	port = "8001"
